on: 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows
          - mac
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add QEMU for cross-compile support
        run: docker run --privileged --rm tonistiigi/binfmt --install all
        if: matrix.arch != 'amd64' && matrix.platform != 'windows' && matrix.platform != 'mac'
      - name: Build
        run: task build-${{matrix.platform}}-${{matrix.arch}}
