on: 
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows
          - mac
          - batocera
        arch:
          - amd64
          - arm64
        include:
          - platform: steamos
            arch: amd64
          - platform: mister
            arch: arm
          - platform: mistex
            arch: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add QEMU for cross-compile support
        run: docker run --privileged --rm tonistiigi/binfmt --install all
        if: matrix.arch != 'amd64' && matrix.platform != 'windows' && matrix.platform != 'mac'
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm
          use: true
          install: true
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3
      - name: Add cache override
        run: echo CACHE_ARGS=\"--load --cache-to type=gha,mode=max,repository=${GITHUB_REPOSITORY} --cache-from type=gha\" > .env
        if: matrix.platform != 'windows' && matrix.platform != 'mac'
      - name: Build
        run: task build-${{matrix.platform}}-${{matrix.arch}}
